name: Build

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      build_exist: ${{ steps.build-exist.outputs.build_exist }}
      upstream_ver: ${{ steps.upstream-ver.outputs.upstream_ver }}
    steps:
      - name: Get repo tags
        run: |
          repo_tags=$(curl -sSL "https://api.github.com/repos/$GITHUB_REPOSITORY/releases" | jq '.[].tag_name')
          echo "repo_tags=$repo_tags" >> "$GITHUB_ENV"
      - name: Get upstream version
        id: upstream-ver
        run: |
          curl -SL 'https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=grub-improved-luks2-git' -o "PKGBUILD"
          pkgver=$(grep -oP "^pkgver='?\K[\d\.]+" './PKGBUILD')
          pkgrel="$(grep -oP "^pkgrel=\K\d+" './PKGBUILD')"
          echo "upstream_ver=${pkgver}-${pkgrel}" >> "$GITHUB_ENV"
          echo "upstream_ver=$upstream_ver" >> "$GITHUB_OUTPUT"
      - name: Check if build exist
        id: build-exist
        run: |
          if echo "$repo_tags" | grep -q "$upstream_ver"; then
            echo "build_exist=true" >> "$GITHUB_OUTPUT"
          else
            echo "build_exist=false" >> "$GITHUB_OUTPUT"
          fi
  build_and_release:
    if: needs.test.outputs.build_exist == 'false'
    needs: test
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    timeout-minutes: 60
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Enable root to run makepkg
        run: |
          sed -i '/E_ROOT/d' /usr/bin/makepkg
      - name: Install git
        run: |
          pacman -Syu --noconfirm git
      - name: Install build deps
        run: |
          git clone 'https://aur.archlinux.org/bdf-unifont.git'
          cd bdf-unifont/
          gpg --recv-key 95D2E9AB8740D8046387FD151A09227B1F435A33
          makepkg -si --noconfirm
      - name: Clone repo
        run: |
          git clone 'https://aur.archlinux.org/grub-improved-luks2-git.git'
      - name: Build
        working-directory: ./grub-improved-luks2-git
        run: |
          makepkg -s --noconfirm
      - name: Generate hashsums
        working-directory: ./grub-improved-luks2-git
        run: |
          sha256sum *.zst > SHA256SUMS
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{needs.test.outputs.upstream_ver}}
          body: ${{needs.test.outputs.upstream_ver}}
          commit: main
          makeLatest: true
          artifacts: "./grub-improved-luks2-git/*.zst,./grub-improved-luks2-git/SHA256SUMS"
