name: Build

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      repo_tags: ${{ steps.repo-tags.outputs.repo_tags }}
      upstream_ver: ${{ steps.upstream-ver.outputs.upstream_ver }}
    steps:
      - name: Get repo tags
        id: repo-tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          {
            echo 'repo_tags<<EOF'
            gh api /repos/$GITHUB_REPOSITORY/releases | jq '.[].tag_name'
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Get upstream version
        id: upstream-ver
        run: |
          curl -SL 'https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=grub-improved-luks2-git' -o "PKGBUILD"
          . "PKGBUILD"
          echo "upstream_ver=${pkgver}-${pkgrel}" >> "$GITHUB_OUTPUT"
  build_and_release:
    needs: test
    if: ${{ ! contains(needs.test.outputs.repo_tags, needs.test.outputs.upstream_ver) }}
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    timeout-minutes: 60
    permissions:
      contents: write
    steps:
      - name: Upstream version
        run: |
          echo ${{ needs.test.outputs.upstream_ver }}
      - uses: actions/checkout@v4
      - name: Enable root to run makepkg
        run: |
          sed -i '/E_ROOT/d' /usr/bin/makepkg
      - name: Install git
        run: |
          pacman -Syu --noconfirm git
      - name: Install build deps
        run: |
          git clone 'https://aur.archlinux.org/bdf-unifont.git'
          cd bdf-unifont/
          gpg --recv-key 95D2E9AB8740D8046387FD151A09227B1F435A33
          makepkg -si --noconfirm
      - name: Clone repo
        run: |
          git clone 'https://aur.archlinux.org/grub-improved-luks2-git.git'
      - name: Build
        working-directory: ./grub-improved-luks2-git
        run: |
          makepkg -s --noconfirm
      - name: Build
        working-directory: ./grub-improved-luks2-git
        run: |
          ls -l
          . "./PKGBUILD"
          echo "${pkgver}-${pkgrel}"
      - name: Generate hashsums
        working-directory: ./grub-improved-luks2-git
        run: |
          sha256sum *.zst > SHA256SUMS
