name: Build

on:
  schedule:
    - cron: "15 3 * * 1"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      repo_tags: ${{ steps.repo-tags.outputs.repo_tags }}
      upstream_ver: ${{ steps.upstream-ver.outputs.upstream_ver }}
    steps:
      - name: Get repo tags
        id: repo-tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          {
            echo 'repo_tags<<EOF'
            gh api /repos/$GITHUB_REPOSITORY/releases | jq '.[].tag_name'
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Get upstream version
        id: upstream-ver
        run: |
          curl -SL 'https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=grub-improved-luks2-git' -o "PKGBUILD"
          . "PKGBUILD"

          latest_tag="$(gh api /repos/$GITHUB_REPOSITORY/tags | jq -r '.[0].name')"
          hash=$(gh api -H "Accept: application/vnd.github.sha" /repos/$GITHUB_REPOSITORY/commits/master)
          count="$(gh api /repos/$GITHUB_REPOSITORY/compare/${latest_tag}...${hash} | jq '.total_commits')"
          shorthash=$(printf "$hash" | grep -oE '^\w{9}')

          echo "upstream_ver=$(echo $latest_tag | sed 's/grub.//').r${count}.g${shorthash}-${pkgrel}" >> "$GITHUB_OUTPUT"
          echo "$GITHUB_OUTPUT" | grep "upstream_ver"
  # build_and_release:
  #   needs: test
  #   if: ${{ ! contains(needs.test.outputs.repo_tags, needs.test.outputs.upstream_ver) }}
  #   runs-on: ubuntu-latest
  #   container: archlinux:base-devel
  #   timeout-minutes: 60
  #   permissions:
  #     contents: write
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Enable root to run makepkg
  #       run: |
  #         sed -i '/E_ROOT/d' /usr/bin/makepkg
  #         sed -i 's/ debug / !debug /g' /etc/makepkg.conf
  #     - name: Install git
  #       run: |
  #         pacman -Syu --noconfirm git
  #     - name: Install build deps
  #       run: |
  #         git clone 'https://aur.archlinux.org/bdf-unifont.git'
  #         cd bdf-unifont/
  #         gpg --recv-key 95D2E9AB8740D8046387FD151A09227B1F435A33
  #         makepkg -si --noconfirm
  #     - name: Clone repo
  #       run: |
  #         git clone 'https://aur.archlinux.org/grub-improved-luks2-git.git'
  #     - name: Switch to mirror
  #       working-directory: ./grub-improved-luks2-git
  #       run: |
  #         sed -ir 's|https:\/\/git\.savannah\.gnu\.org\/git\/grub\.git|https://github.com/curbengh/grub-mirror|' "PKGBUILD"
  #         sed -ir 's|https:\/\/git\.savannah\.gnu\.org\/git\/grub-extras\.git|https://github.com/curbengh/grub-extras-mirror|' "PKGBUILD"
  #         sed -ir 's|https:\/\/git\.savannah\.gnu\.org\/git\/gnulib\.git|https://github.com/curbengh/gnulib-mirror|' "PKGBUILD"
  #     - name: Build
  #       working-directory: ./grub-improved-luks2-git
  #       run: |
  #         makepkg -s --noconfirm
  #     - name: Get development version
  #       working-directory: ./grub-improved-luks2-git
  #       run: |
  #         echo "pkgver=$(grep -oP '^pkgver = \K[\w.-]+' 'pkg/grub-improved-luks2-git/.PKGINFO')" >> "$GITHUB_ENV"
  #     - name: Generate hashsums
  #       working-directory: ./grub-improved-luks2-git
  #       run: |
  #         sha256sum *.zst > SHA256SUMS
  #     - uses: ncipollo/release-action@v1
  #       with:
  #         tag: ${{ env.pkgver }}
  #         body: ${{ env.pkgver }}
  #         commit: main
  #         makeLatest: true
  #         artifacts: "./grub-improved-luks2-git/*.zst,./grub-improved-luks2-git/SHA256SUMS"
